nelmio_api_doc:
    documentation:
        info:
            title: B2B
            description: Un projet d'api en B2B
            version: 1.0.0
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: user3@mail.com
                        password:
                            type: string
                            default: pass123
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/api(?!/doc$|/login_check$)
